name: caching
on: [push]
jobs:
  caching-dependecies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: npm ci
      - name: use Axios
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios')
            const url = "https://jsonplaceholder.typicode.com/posts/1"
            const res = await axios.get(url, {
             headers: {
               Accepts: 'text/plain'
             }
            })
            console.log("Joke:::>>>> ", res.data)
