# To cache files, we use the actions/cache@v4, and provide a key and a path.
# We can retrieve the cached files by matching the provided key
# restore-keys is another set of keys to retrieve the cached files, can match part of it not exactly matching
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
name: caching-simple
on: [push]
jobs:
  with-caching:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        env:
          cache-name: npm-cache
        with:
          path: ~/.npm
          key: ${{runner.os}}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - if: ${{ steps.cache-dependencies == 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'
      - name: Install dependencies
        run: npm install

      - name: check cache status
        run: echo "cache-hit status :::::>>" ${{steps.cache-dependencies.outputs.cache-hit}}
