# To cache files, we use the actions/cache@v4, and provide a key and a path.
# We can retrieve the cached files by matching the provided key
# restore-keys is another set of keys to retrieve the cached files, can match part of it not exactly matching
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
name: caching
on: [push]
jobs:
  with-caching:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache-node-modules
        id: cache-npm-i
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: npm-cache
          restore-keys: |
            ${{runner.os}}-build-${{env.cache-name}}
            ${{runner.os}}-build
            ${{runner.os}}-

      - name: print cached files
        run: echo ${{toJson(steps.cache-npm-i.outputs)}}

      - name: check cache status
        run: echo "cache-hit status :::::>>" ${{steps.cache-npm-i.outputs.cache-hit}}

  without-caching:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: npm ci
      - name: use Axios
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios')
            const url = "https://jsonplaceholder.typicode.com/posts/1"
            const res = await axios.get(url, {
             headers: {
               Accept: 'text/plain'
             }
            })
            console.log("Post:::>>>> ", res.data)
